//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR02200BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR02100BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR02100BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR02100BackResources.PMR02100BackResources_msgrsc", typeof(PMR02100BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        internal static string CHECKBOX_CUSTOMER_INFORMATION {
            get {
                return ResourceManager.GetString("CHECKBOX_CUSTOMER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Group.
        /// </summary>
        internal static string CHECKBOX_INVOICE_GROUP {
            get {
                return ResourceManager.GetString("CHECKBOX_INVOICE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        internal static string CHECKBOX_PENALTY {
            get {
                return ResourceManager.GetString("CHECKBOX_PENALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Receipt.
        /// </summary>
        internal static string CHECKBOX_UNALLOCATED_RECEIPT {
            get {
                return ResourceManager.GetString("CHECKBOX_UNALLOCATED_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-30 Days.
        /// </summary>
        internal static string COLOUMN_1_30DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_1_30DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 120 Days.
        /// </summary>
        internal static string COLOUMN_120DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_120DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 30 Days.
        /// </summary>
        internal static string COLOUMN_30DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_30DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31-60 Days.
        /// </summary>
        internal static string COLOUMN_31_60DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_31_60DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 60 Days.
        /// </summary>
        internal static string COLOUMN_60DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_60DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61-90 Days.
        /// </summary>
        internal static string COLOUMN_61_90DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_61_90DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 90 Days.
        /// </summary>
        internal static string COLOUMN_90DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_90DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 91-120 Days.
        /// </summary>
        internal static string COLOUMN_91_120DAYS {
            get {
                return ResourceManager.GetString("COLOUMN_91_120DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string COLOUMN_ADDRESS {
            get {
                return ResourceManager.GetString("COLOUMN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Total.
        /// </summary>
        internal static string COLOUMN_AGE_TOTAL {
            get {
                return ResourceManager.GetString("COLOUMN_AGE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string COLOUMN_AMMOUNT {
            get {
                return ResourceManager.GetString("COLOUMN_AMMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string COLOUMN_CURR {
            get {
                return ResourceManager.GetString("COLOUMN_CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string COLOUMN_CURRENT {
            get {
                return ResourceManager.GetString("COLOUMN_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string COLOUMN_CUSTOMER {
            get {
                return ResourceManager.GetString("COLOUMN_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string COLOUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLOUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string COLOUMN_DUE_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string COLOUMN_EMAIL {
            get {
                return ResourceManager.GetString("COLOUMN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string COLOUMN_INVOICE_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_INVOICE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string COLOUMN_INVOICE_NO {
            get {
                return ResourceManager.GetString("COLOUMN_INVOICE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group.
        /// </summary>
        internal static string COLOUMN_JRN_GRP {
            get {
                return ResourceManager.GetString("COLOUMN_JRN_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Due.
        /// </summary>
        internal static string COLOUMN_NOT_DUE {
            get {
                return ResourceManager.GetString("COLOUMN_NOT_DUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string COLOUMN_ORIGINAL {
            get {
                return ResourceManager.GetString("COLOUMN_ORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        internal static string COLOUMN_OUTSTANDING {
            get {
                return ResourceManager.GetString("COLOUMN_OUTSTANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        internal static string COLOUMN_PENALTY {
            get {
                return ResourceManager.GetString("COLOUMN_PENALTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string COLOUMN_PHONE {
            get {
                return ResourceManager.GetString("COLOUMN_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string COLOUMN_TOTAL {
            get {
                return ResourceManager.GetString("COLOUMN_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string COLOUMN_TYPE {
            get {
                return ResourceManager.GetString("COLOUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Receipt.
        /// </summary>
        internal static string COLOUMN_UNALLOCATED_RECEIPT {
            get {
                return ResourceManager.GetString("COLOUMN_UNALLOCATED_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string COLOUMN_UNIT_NAME {
            get {
                return ResourceManager.GetString("COLOUMN_UNIT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FOOTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FOOTER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string FOOTER_GRAND_TOTAL {
            get {
                return ResourceManager.GetString("FOOTER_GRAND_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total Based on.
        /// </summary>
        internal static string FOOTER_SUB_TOTAL_BASED_ON_JRN_GRP {
            get {
                return ResourceManager.GetString("FOOTER_SUB_TOTAL_BASED_ON_JRN_GRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string HEADER_CUSTOMER {
            get {
                return ResourceManager.GetString("HEADER_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string HEADER_CUT_OFF_DATE {
            get {
                return ResourceManager.GetString("HEADER_CUT_OFF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Zero Balance.
        /// </summary>
        internal static string HEADER_INCLUDE_ZERO_BALANCE {
            get {
                return ResourceManager.GetString("HEADER_INCLUDE_ZERO_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group.
        /// </summary>
        internal static string HEADER_JOURNAL_GROUP {
            get {
                return ResourceManager.GetString("HEADER_JOURNAL_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOI/Aggrement No..
        /// </summary>
        internal static string HEADER_LOI_AGGREMENT_NO {
            get {
                return ResourceManager.GetString("HEADER_LOI_AGGREMENT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string HEADER_PROPERTY {
            get {
                return ResourceManager.GetString("HEADER_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string HEADER_REPORT_TYPE {
            get {
                return ResourceManager.GetString("HEADER_REPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Age Total.
        /// </summary>
        internal static string HEADER_SHOW_AGE_TOTAL {
            get {
                return ResourceManager.GetString("HEADER_SHOW_AGE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Date.
        /// </summary>
        internal static string HEADER_STATEMENT_DATE {
            get {
                return ResourceManager.GetString("HEADER_STATEMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string HEADER_UNIT_NAME {
            get {
                return ResourceManager.GetString("HEADER_UNIT_NAME", resourceCulture);
            }
        }
    }
}
