//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM08500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM08500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM08500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM08500FrontResources.GSM08500FrontResources_msgrsc", typeof(GSM08500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Category.
        /// </summary>
        internal static string _accCategory {
            get {
                return ResourceManager.GetString("_accCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _accountName {
            get {
                return ResourceManager.GetString("_accountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _accountNo {
            get {
                return ResourceManager.GetString("_accountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string _activate {
            get {
                return ResourceManager.GetString("_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _active {
            get {
                return ResourceManager.GetString("_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        internal static string _balanceSheet {
            get {
                return ResourceManager.GetString("_balanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS / IS.
        /// </summary>
        internal static string _bsis {
            get {
                return ResourceManager.GetString("_bsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _cancel {
            get {
                return ResourceManager.GetString("_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _close {
            get {
                return ResourceManager.GetString("_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string _company {
            get {
                return ResourceManager.GetString("_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        internal static string _companyId {
            get {
                return ResourceManager.GetString("_companyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string _companyName {
            get {
                return ResourceManager.GetString("_companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Form.
        /// </summary>
        internal static string _copyForm {
            get {
                return ResourceManager.GetString("_copyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string _credit {
            get {
                return ResourceManager.GetString("_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D / C.
        /// </summary>
        internal static string _dc {
            get {
                return ResourceManager.GetString("_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string _debit {
            get {
                return ResourceManager.GetString("_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string _errorMessage {
            get {
                return ResourceManager.GetString("_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string _fromAcc {
            get {
                return ResourceManager.GetString("_fromAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string _inactive {
            get {
                return ResourceManager.GetString("_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string _incomeStatement {
            get {
                return ResourceManager.GetString("_incomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _invalid {
            get {
                return ResourceManager.GetString("_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _print {
            get {
                return ResourceManager.GetString("_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inactive Account.
        /// </summary>
        internal static string _printInactiveAccount {
            get {
                return ResourceManager.GetString("_printInactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Statistic Account.
        /// </summary>
        internal static string _printStatisticAccount {
            get {
                return ResourceManager.GetString("_printStatisticAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _process {
            get {
                return ResourceManager.GetString("_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Excel.
        /// </summary>
        internal static string _saveToExcel {
            get {
                return ResourceManager.GetString("_saveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string _sortBy {
            get {
                return ResourceManager.GetString("_sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _sourceFile {
            get {
                return ResourceManager.GetString("_sourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _template {
            get {
                return ResourceManager.GetString("_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        internal static string _toAcc {
            get {
                return ResourceManager.GetString("_toAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _totalRows {
            get {
                return ResourceManager.GetString("_totalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _updateBy {
            get {
                return ResourceManager.GetString("_updateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _updateDate {
            get {
                return ResourceManager.GetString("_updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _upload {
            get {
                return ResourceManager.GetString("_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _valid {
            get {
                return ResourceManager.GetString("_valid", resourceCulture);
            }
        }
    }
}
