//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR01000BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TXR00100BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TXR00100BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRX00100BackResources.TXR00100BackResources_msgrsc", typeof(TXR00100BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggrement No..
        /// </summary>
        internal static string COLOUMN_AGGREMENT_NO {
            get {
                return ResourceManager.GetString("COLOUMN_AGGREMENT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curr..
        /// </summary>
        internal static string COLOUMN_CURR {
            get {
                return ResourceManager.GetString("COLOUMN_CURR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string COLOUMN_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("COLOUMN_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string COLOUMN_INVOICE_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_INVOICE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string COLOUMN_INVOICE_NO {
            get {
                return ResourceManager.GetString("COLOUMN_INVOICE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Address.
        /// </summary>
        internal static string COLOUMN_TAX_ADDRESS {
            get {
                return ResourceManager.GetString("COLOUMN_TAX_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Description.
        /// </summary>
        internal static string COLOUMN_UNIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLOUMN_UNIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WH Tax Amount.
        /// </summary>
        internal static string COLOUMN_WH_TAX_AMOUNT {
            get {
                return ResourceManager.GetString("COLOUMN_WH_TAX_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WH Tax Collect.
        /// </summary>
        internal static string COLOUMN_WH_TAX_COLLECT {
            get {
                return ResourceManager.GetString("COLOUMN_WH_TAX_COLLECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WH Tax Slip Amount.
        /// </summary>
        internal static string COLOUMN_WH_TAX_SLIP_AMOUNT {
            get {
                return ResourceManager.GetString("COLOUMN_WH_TAX_SLIP_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WH Tax Slip Date.
        /// </summary>
        internal static string COLOUMN_WH_TAX_SLIP_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_WH_TAX_SLIP_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WH Tax Slip No..
        /// </summary>
        internal static string COLOUMN_WH_TAX_SLIP_NO {
            get {
                return ResourceManager.GetString("COLOUMN_WH_TAX_SLIP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string HEADER_PROPERTY {
            get {
                return ResourceManager.GetString("HEADER_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Period.
        /// </summary>
        internal static string HEADER_TAX_PERIOD {
            get {
                return ResourceManager.GetString("HEADER_TAX_PERIOD", resourceCulture);
            }
        }
    }
}
