//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM01000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM01000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM01000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM01000FrontResources.GSM01000FrontResources_msgrsc", typeof(GSM01000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _account {
            get {
                return ResourceManager.GetString("_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _accountName {
            get {
                return ResourceManager.GetString("_accountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _accountNo {
            get {
                return ResourceManager.GetString("_accountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _active {
            get {
                return ResourceManager.GetString("_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Center.
        /// </summary>
        internal static string _assignCenter {
            get {
                return ResourceManager.GetString("_assignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign COA.
        /// </summary>
        internal static string _assignCOA {
            get {
                return ResourceManager.GetString("_assignCOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign User.
        /// </summary>
        internal static string _assignUser {
            get {
                return ResourceManager.GetString("_assignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        internal static string _balanceSheet {
            get {
                return ResourceManager.GetString("_balanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS / IS.
        /// </summary>
        internal static string _bsis {
            get {
                return ResourceManager.GetString("_bsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _cancel {
            get {
                return ResourceManager.GetString("_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        internal static string _cashflow {
            get {
                return ResourceManager.GetString("_cashflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code.
        /// </summary>
        internal static string _centerCode {
            get {
                return ResourceManager.GetString("_centerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string _centerName {
            get {
                return ResourceManager.GetString("_centerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Restriction.
        /// </summary>
        internal static string _centerRestriction {
            get {
                return ResourceManager.GetString("_centerRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        internal static string _companyID {
            get {
                return ResourceManager.GetString("_companyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string _companyName {
            get {
                return ResourceManager.GetString("_companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Form.
        /// </summary>
        internal static string _copyForm {
            get {
                return ResourceManager.GetString("_copyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _createdBy {
            get {
                return ResourceManager.GetString("_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _createdDate {
            get {
                return ResourceManager.GetString("_createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D / C.
        /// </summary>
        internal static string _dc {
            get {
                return ResourceManager.GetString("_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account.
        /// </summary>
        internal static string _GroupOfAccount {
            get {
                return ResourceManager.GetString("_GroupOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account Name.
        /// </summary>
        internal static string _GroupOfAccountName {
            get {
                return ResourceManager.GetString("_GroupOfAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string _inactive {
            get {
                return ResourceManager.GetString("_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string _incomeStatement {
            get {
                return ResourceManager.GetString("_incomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _print {
            get {
                return ResourceManager.GetString("_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _process {
            get {
                return ResourceManager.GetString("_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _template {
            get {
                return ResourceManager.GetString("_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _updateBy {
            get {
                return ResourceManager.GetString("_updateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _updateDate {
            get {
                return ResourceManager.GetString("_updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _upload {
            get {
                return ResourceManager.GetString("_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string _userID {
            get {
                return ResourceManager.GetString("_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string _username {
            get {
                return ResourceManager.GetString("_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Restriction.
        /// </summary>
        internal static string _userRestriction {
            get {
                return ResourceManager.GetString("_userRestriction", resourceCulture);
            }
        }
    }
}
