//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM01000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM01000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM01000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM01000FrontResources.GSM01000FrontResources_msgrsc", typeof(GSM01000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Category.
        /// </summary>
        internal static string _AccCategory {
            get {
                return ResourceManager.GetString("_AccCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _account {
            get {
                return ResourceManager.GetString("_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _accountName {
            get {
                return ResourceManager.GetString("_accountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _accountNo {
            get {
                return ResourceManager.GetString("_accountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _active {
            get {
                return ResourceManager.GetString("_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Center.
        /// </summary>
        internal static string _assignCenter {
            get {
                return ResourceManager.GetString("_assignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign COA.
        /// </summary>
        internal static string _assignCOA {
            get {
                return ResourceManager.GetString("_assignCOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign User.
        /// </summary>
        internal static string _assignUser {
            get {
                return ResourceManager.GetString("_assignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        internal static string _balanceSheet {
            get {
                return ResourceManager.GetString("_balanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS / IS.
        /// </summary>
        internal static string _bsis {
            get {
                return ResourceManager.GetString("_bsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _cancel {
            get {
                return ResourceManager.GetString("_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow.
        /// </summary>
        internal static string _cashflow {
            get {
                return ResourceManager.GetString("_cashflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashFlow Code.
        /// </summary>
        internal static string _cashflowcode {
            get {
                return ResourceManager.GetString("_cashflowcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashFlow Group Code.
        /// </summary>
        internal static string _cashflowgroupcode {
            get {
                return ResourceManager.GetString("_cashflowgroupcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code.
        /// </summary>
        internal static string _centerCode {
            get {
                return ResourceManager.GetString("_centerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string _centerName {
            get {
                return ResourceManager.GetString("_centerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Restriction.
        /// </summary>
        internal static string _centerRestriction {
            get {
                return ResourceManager.GetString("_centerRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _close {
            get {
                return ResourceManager.GetString("_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string _company {
            get {
                return ResourceManager.GetString("_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        internal static string _companyID {
            get {
                return ResourceManager.GetString("_companyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string _companyName {
            get {
                return ResourceManager.GetString("_companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Form.
        /// </summary>
        internal static string _copyForm {
            get {
                return ResourceManager.GetString("_copyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _createdBy {
            get {
                return ResourceManager.GetString("_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _createdDate {
            get {
                return ResourceManager.GetString("_createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string _credit {
            get {
                return ResourceManager.GetString("_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D / C.
        /// </summary>
        internal static string _dc {
            get {
                return ResourceManager.GetString("_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string _debit {
            get {
                return ResourceManager.GetString("_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string _errorMessage {
            get {
                return ResourceManager.GetString("_errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        internal static string _fromAcc {
            get {
                return ResourceManager.GetString("_fromAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Group Of Account.
        /// </summary>
        internal static string _fromGOA {
            get {
                return ResourceManager.GetString("_fromGOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account Code.
        /// </summary>
        internal static string _goaCode {
            get {
                return ResourceManager.GetString("_goaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account Category.
        /// </summary>
        internal static string _groupOfAccCategory {
            get {
                return ResourceManager.GetString("_groupOfAccCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account.
        /// </summary>
        internal static string _GroupOfAccount {
            get {
                return ResourceManager.GetString("_GroupOfAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of Account Name.
        /// </summary>
        internal static string _GroupOfAccountName {
            get {
                return ResourceManager.GetString("_GroupOfAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string _inactive {
            get {
                return ResourceManager.GetString("_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        internal static string _incomeStatement {
            get {
                return ResourceManager.GetString("_incomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _invalid {
            get {
                return ResourceManager.GetString("_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonActiveDate.
        /// </summary>
        internal static string _NonActiveDate {
            get {
                return ResourceManager.GetString("_NonActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _notes {
            get {
                return ResourceManager.GetString("_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _print {
            get {
                return ResourceManager.GetString("_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Account.
        /// </summary>
        internal static string _printAccount {
            get {
                return ResourceManager.GetString("_printAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Center Restriction.
        /// </summary>
        internal static string _printCenterRestric {
            get {
                return ResourceManager.GetString("_printCenterRestric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print COA.
        /// </summary>
        internal static string _printCOA {
            get {
                return ResourceManager.GetString("_printCOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print GOA.
        /// </summary>
        internal static string _printGOA {
            get {
                return ResourceManager.GetString("_printGOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inactive Account.
        /// </summary>
        internal static string _printInactiveAcc {
            get {
                return ResourceManager.GetString("_printInactiveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print User Restriction.
        /// </summary>
        internal static string _printUserRestric {
            get {
                return ResourceManager.GetString("_printUserRestric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _process {
            get {
                return ResourceManager.GetString("_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _saveToExcel {
            get {
                return ResourceManager.GetString("_saveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string _sortBy {
            get {
                return ResourceManager.GetString("_sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _sourceFile {
            get {
                return ResourceManager.GetString("_sourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _template {
            get {
                return ResourceManager.GetString("_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        internal static string _toAcc {
            get {
                return ResourceManager.GetString("_toAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Group Of Account.
        /// </summary>
        internal static string _toGOA {
            get {
                return ResourceManager.GetString("_toGOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _totalRows {
            get {
                return ResourceManager.GetString("_totalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _updateBy {
            get {
                return ResourceManager.GetString("_updateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _updateDate {
            get {
                return ResourceManager.GetString("_updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _upload {
            get {
                return ResourceManager.GetString("_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string _userID {
            get {
                return ResourceManager.GetString("_userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string _username {
            get {
                return ResourceManager.GetString("_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Restriction.
        /// </summary>
        internal static string _userRestriction {
            get {
                return ResourceManager.GetString("_userRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _valid {
            get {
                return ResourceManager.GetString("_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Code cannot be empty!
        ///.
        /// </summary>
        internal static string _validationCashflow {
            get {
                return ResourceManager.GetString("_validationCashflow", resourceCulture);
            }
        }
    }
}
