//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMR01000BackResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMR01000BackResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMR01000BackResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMR01000BackResources.PMR01000BackResources_msgrsc", typeof(PMR01000BackResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string COLOUMN_ACCOUNT_NAME {
            get {
                return ResourceManager.GetString("COLOUMN_ACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string COLOUMN_ACCOUNT_NO {
            get {
                return ResourceManager.GetString("COLOUMN_ACCOUNT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string COLOUMN_ADJUSTMENT {
            get {
                return ResourceManager.GetString("COLOUMN_ADJUSTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string COLOUMN_AMOUNT {
            get {
                return ResourceManager.GetString("COLOUMN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string COLOUMN_BUILDING {
            get {
                return ResourceManager.GetString("COLOUMN_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        internal static string COLOUMN_CREDIT_NOTE {
            get {
                return ResourceManager.GetString("COLOUMN_CREDIT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string COLOUMN_CURRENCY {
            get {
                return ResourceManager.GetString("COLOUMN_CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string COLOUMN_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("COLOUMN_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Off Date.
        /// </summary>
        internal static string COLOUMN_CUT_OFF_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_CUT_OFF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string COLOUMN_DEPOSIT {
            get {
                return ResourceManager.GetString("COLOUMN_DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount.
        /// </summary>
        internal static string COLOUMN_DEPOSIT_AMOUNT {
            get {
                return ResourceManager.GetString("COLOUMN_DEPOSIT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Balance.
        /// </summary>
        internal static string COLOUMN_DEPOSIT_BALANCE {
            get {
                return ResourceManager.GetString("COLOUMN_DEPOSIT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepositDate.
        /// </summary>
        internal static string COLOUMN_DEPOSIT_DATE {
            get {
                return ResourceManager.GetString("COLOUMN_DEPOSIT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string COLOUMN_INVOICE_NO {
            get {
                return ResourceManager.GetString("COLOUMN_INVOICE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Deposit Balance.
        /// </summary>
        internal static string COLOUMN_LOCAL_DEPOSIT_BALANCE {
            get {
                return ResourceManager.GetString("COLOUMN_LOCAL_DEPOSIT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Deposit Balance.
        /// </summary>
        internal static string COLOUMN_NBASE_DEPOSIT_BALANCE {
            get {
                return ResourceManager.GetString("COLOUMN_NBASE_DEPOSIT_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status.
        /// </summary>
        internal static string COLOUMN_PAYMENT_STATUS {
            get {
                return ResourceManager.GetString("COLOUMN_PAYMENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string COLOUMN_PERIOD {
            get {
                return ResourceManager.GetString("COLOUMN_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string COLOUMN_REFERENCE_NO {
            get {
                return ResourceManager.GetString("COLOUMN_REFERENCE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string COLOUMN_REFUND {
            get {
                return ResourceManager.GetString("COLOUMN_REFUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string COLOUMN_STATUS {
            get {
                return ResourceManager.GetString("COLOUMN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string COLOUMN_TRANSACTION {
            get {
                return ResourceManager.GetString("COLOUMN_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No.
        /// </summary>
        internal static string COLOUMN_TRANSACTION__NO {
            get {
                return ResourceManager.GetString("COLOUMN_TRANSACTION__NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string COLOUMN_TRANSACTION_TYPE {
            get {
                return ResourceManager.GetString("COLOUMN_TRANSACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string COLOUMN_TYPE {
            get {
                return ResourceManager.GetString("COLOUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Desc.
        /// </summary>
        internal static string COLOUMN_UNIT_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLOUMN_UNIT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Building.
        /// </summary>
        internal static string HEADER_FROM_BUILDING {
            get {
                return ResourceManager.GetString("HEADER_FROM_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Period.
        /// </summary>
        internal static string HEADER_FROM_PERIOD {
            get {
                return ResourceManager.GetString("HEADER_FROM_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Transaction Type.
        /// </summary>
        internal static string HEADER_FROM_TRANSACTION_TYPE {
            get {
                return ResourceManager.GetString("HEADER_FROM_TRANSACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Type.
        /// </summary>
        internal static string HEADER_FROM_TYPE {
            get {
                return ResourceManager.GetString("HEADER_FROM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Building.
        /// </summary>
        internal static string HEADER_TO_BUILDING {
            get {
                return ResourceManager.GetString("HEADER_TO_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Period.
        /// </summary>
        internal static string HEADER_TO_PERIOD {
            get {
                return ResourceManager.GetString("HEADER_TO_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Transaction Type.
        /// </summary>
        internal static string HEADER_TO_TRANSACTION_TYPE {
            get {
                return ResourceManager.GetString("HEADER_TO_TRANSACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Type.
        /// </summary>
        internal static string HEADER_TO_TYPE {
            get {
                return ResourceManager.GetString("HEADER_TO_TYPE", resourceCulture);
            }
        }
    }
}
