//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLT00600FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLT00600FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLT00600FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLT00600FrontResources.GLT00600FrontResources_msgrsc", typeof(GLT00600FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _AccountName {
            get {
                return ResourceManager.GetString("_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _AccountNo {
            get {
                return ResourceManager.GetString("_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _add {
            get {
                return ResourceManager.GetString("_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammount.
        /// </summary>
        internal static string _ammount {
            get {
                return ResourceManager.GetString("_ammount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string _approve {
            get {
                return ResourceManager.GetString("_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string _baseCurrency {
            get {
                return ResourceManager.GetString("_baseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Rate.
        /// </summary>
        internal static string _baseRate {
            get {
                return ResourceManager.GetString("_baseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string _btnApprove {
            get {
                return ResourceManager.GetString("_btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _btnCancel {
            get {
                return ResourceManager.GetString("_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string _btnCommit {
            get {
                return ResourceManager.GetString("_btnCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string _btnSubmit {
            get {
                return ResourceManager.GetString("_btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Commit.
        /// </summary>
        internal static string _btnUndoCommit {
            get {
                return ResourceManager.GetString("_btnUndoCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Submit.
        /// </summary>
        internal static string _btnUndoSubmit {
            get {
                return ResourceManager.GetString("_btnUndoSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _cancel {
            get {
                return ResourceManager.GetString("_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string _center {
            get {
                return ResourceManager.GetString("_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string _commit {
            get {
                return ResourceManager.GetString("_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string _copy {
            get {
                return ResourceManager.GetString("_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR (Base).
        /// </summary>
        internal static string _crBase {
            get {
                return ResourceManager.GetString("_crBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _createdBy {
            get {
                return ResourceManager.GetString("_createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _createdDate {
            get {
                return ResourceManager.GetString("_createdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string _credit {
            get {
                return ResourceManager.GetString("_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR (Local).
        /// </summary>
        internal static string _crlocal {
            get {
                return ResourceManager.GetString("_crlocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _currency {
            get {
                return ResourceManager.GetString("_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string _currencyRate {
            get {
                return ResourceManager.GetString("_currencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB (Base).
        /// </summary>
        internal static string _dbBase {
            get {
                return ResourceManager.GetString("_dbBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB (Local).
        /// </summary>
        internal static string _dblocal {
            get {
                return ResourceManager.GetString("_dblocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/C.
        /// </summary>
        internal static string _dc {
            get {
                return ResourceManager.GetString("_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string _debit {
            get {
                return ResourceManager.GetString("_debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string _delete {
            get {
                return ResourceManager.GetString("_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _department {
            get {
                return ResourceManager.GetString("_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _desc {
            get {
                return ResourceManager.GetString("_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string _docDate {
            get {
                return ResourceManager.GetString("_docDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string _docNo_ {
            get {
                return ResourceManager.GetString("_docNo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq..
        /// </summary>
        internal static string _freq_ {
            get {
                return ResourceManager.GetString("_freq.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Period.
        /// </summary>
        internal static string _journalPeriod {
            get {
                return ResourceManager.GetString("_journalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string _localCurrency {
            get {
                return ResourceManager.GetString("_localCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Ref. No..
        /// </summary>
        internal static string _masterRefNo {
            get {
                return ResourceManager.GetString("_masterRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string _modify {
            get {
                return ResourceManager.GetString("_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string _no {
            get {
                return ResourceManager.GetString("_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prelist.
        /// </summary>
        internal static string _prelist {
            get {
                return ResourceManager.GetString("_prelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Approval.
        /// </summary>
        internal static string _rapidApprove {
            get {
                return ResourceManager.GetString("_rapidApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Commit.
        /// </summary>
        internal static string _rapidCommit {
            get {
                return ResourceManager.GetString("_rapidCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date.
        /// </summary>
        internal static string _referenceDate {
            get {
                return ResourceManager.GetString("_referenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No..
        /// </summary>
        internal static string _referenceNo {
            get {
                return ResourceManager.GetString("_referenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _save {
            get {
                return ResourceManager.GetString("_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _search {
            get {
                return ResourceManager.GetString("_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq..
        /// </summary>
        internal static string _seq {
            get {
                return ResourceManager.GetString("_seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string _showAll {
            get {
                return ResourceManager.GetString("_showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _status {
            get {
                return ResourceManager.GetString("_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        internal static string _totalCredit {
            get {
                return ResourceManager.GetString("_totalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit.
        /// </summary>
        internal static string _totalDebit {
            get {
                return ResourceManager.GetString("_totalDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _updateBy {
            get {
                return ResourceManager.GetString("_updateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _updateDate {
            get {
                return ResourceManager.GetString("_updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is required!.
        /// </summary>
        internal static string _validationAccountNo {
            get {
                return ResourceManager.GetString("_validationAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Document Date first before input Journal Detail!.
        /// </summary>
        internal static string _validationAddEditDocDate {
            get {
                return ResourceManager.GetString("_validationAddEditDocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Document No. first before input Journal Detail!.
        /// </summary>
        internal static string _validationAddEditDocNo {
            get {
                return ResourceManager.GetString("_validationAddEditDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have right to approve this journal!.
        /// </summary>
        internal static string _validationAllowApprove {
            get {
                return ResourceManager.GetString("_validationAllowApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists!.
        /// </summary>
        internal static string _validationAlreadyExist {
            get {
                return ResourceManager.GetString("_validationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string _validationBaseCurrencyBase {
            get {
                return ResourceManager.GetString("_validationBaseCurrencyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate must be greater than 0!.
        /// </summary>
        internal static string _validationBaseCurrencyRate {
            get {
                return ResourceManager.GetString("_validationBaseCurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code is required for Account No..
        /// </summary>
        internal static string _validationCenterCode {
            get {
                return ResourceManager.GetString("_validationCenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to commit this journal? [Yes/No].
        /// </summary>
        internal static string _validationCommit {
            get {
                return ResourceManager.GetString("_validationCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found!.
        /// </summary>
        internal static string _validationDataNotFound {
            get {
                return ResourceManager.GetString("_validationDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this journal?’[Yes/No].
        /// </summary>
        internal static string _validationDelete {
            get {
                return ResourceManager.GetString("_validationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Department!.
        /// </summary>
        internal static string _validationDeptMandatory {
            get {
                return ResourceManager.GetString("_validationDeptMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Description first before input Journal Detail!.
        /// </summary>
        internal static string _validationDescMandatory {
            get {
                return ResourceManager.GetString("_validationDescMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required!.
        /// </summary>
        internal static string _validationDescReq {
            get {
                return ResourceManager.GetString("_validationDescReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Document Date! Document Date cannot be before Current Period!.
        /// </summary>
        internal static string _validationDocumentDateCannot {
            get {
                return ResourceManager.GetString("_validationDocumentDateCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Document No.!.
        /// </summary>
        internal static string _validationInputDocumentNo {
            get {
                return ResourceManager.GetString("_validationInputDocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal amount is not equal to Prelist!.
        /// </summary>
        internal static string _validationJournalAmount {
            get {
                return ResourceManager.GetString("_validationJournalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal amount cannot be 0!.
        /// </summary>
        internal static string _validationJournalAmountCannotZero {
            get {
                return ResourceManager.GetString("_validationJournalAmountCannotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Base Rate must be greater than 0!.
        /// </summary>
        internal static string _validationLocalCurrencyBase {
            get {
                return ResourceManager.GetString("_validationLocalCurrencyBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate must be greater than 0!.
        /// </summary>
        internal static string _validationLocalCurrencyRate {
            get {
                return ResourceManager.GetString("_validationLocalCurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found!.
        /// </summary>
        internal static string _validationNoDataFound {
            get {
                return ResourceManager.GetString("_validationNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to process selected Journal(s)?.
        /// </summary>
        internal static string _validationProcess {
            get {
                return ResourceManager.GetString("_validationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date cannot be before Current Period!.
        /// </summary>
        internal static string _validationReferenceDateCannot {
            get {
                return ResourceManager.GetString("_validationReferenceDateCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No. is required!.
        /// </summary>
        internal static string _validationReferenceRequired {
            get {
                return ResourceManager.GetString("_validationReferenceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input keyword to search!.
        /// </summary>
        internal static string _validationSearchText {
            get {
                return ResourceManager.GetString("_validationSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum search keyword is 3 characters!.
        /// </summary>
        internal static string _validationSearchTextMinimum {
            get {
                return ResourceManager.GetString("_validationSearchTextMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to submit this journal? [Yes/No].
        /// </summary>
        internal static string _validationSubmit {
            get {
                return ResourceManager.GetString("_validationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Journal Approved Successfully!.
        /// </summary>
        internal static string _validationSuccesApprove {
            get {
                return ResourceManager.GetString("_validationSuccesApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Journal Committed Successfully!.
        /// </summary>
        internal static string _validationSuccesCommit {
            get {
                return ResourceManager.GetString("_validationSuccesCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Journal Undo Commit Successfully!.
        /// </summary>
        internal static string _validationSuccesUndoCommit {
            get {
                return ResourceManager.GetString("_validationSuccesUndoCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit Amount must be equal to Total Credit Amount.
        /// </summary>
        internal static string _validationTotalDebitTotalAmount {
            get {
                return ResourceManager.GetString("_validationTotalDebitTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to undo commit this journal? [Yes/No].
        /// </summary>
        internal static string _validationUndoCommit {
            get {
                return ResourceManager.GetString("_validationUndoCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to undo submit this journal? [Yes/No].
        /// </summary>
        internal static string _validationUndoSubmit {
            get {
                return ResourceManager.GetString("_validationUndoSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t saved your changes. Are you sure want to cancel? [Yes/No].
        /// </summary>
        internal static string _validationYouHaventSave {
            get {
                return ResourceManager.GetString("_validationYouHaventSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date.
        /// </summary>
        internal static string _voucherDate {
            get {
                return ResourceManager.GetString("_voucherDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher No..
        /// </summary>
        internal static string _voucherNo {
            get {
                return ResourceManager.GetString("_voucherNo", resourceCulture);
            }
        }
    }
}
